// Generated by scripts/sync-client-profile.mjs. Do not edit manually.
import exampleAudioProductCatalog from "./example-audio-product-catalog.json"
import exampleIndustrialProductCatalog from "./example-industrial-product-catalog.json"
import ngsProductCatalog from "./ngs-product-catalog.json"

export const generatedProductCatalogProfiles = {
  "example-audio": exampleAudioProductCatalog,
  "example-industrial": exampleIndustrialProductCatalog,
  "ngs": ngsProductCatalog,
}
