// Generated by scripts/sync-client-profile.mjs. Do not edit manually.
import exampleAudioPackaging from "./example-audio-product-packaging.json"
import exampleIndustrialPackaging from "./example-industrial-product-packaging.json"
import ngsPackaging from "./ngs-product-packaging.json"

export const generatedProductPackagingProfiles = {
  "example-audio": exampleAudioPackaging,
  "example-industrial": exampleIndustrialPackaging,
  "ngs": ngsPackaging,
}
