// Generated by scripts/sync-client-profile.mjs. Do not edit manually.
import exampleAudioProfile from "./profiles/example-audio.json"
import exampleAudioHomepage from "./profiles/example-audio-homepage.json"
import exampleIndustrialProfile from "./profiles/example-industrial.json"
import exampleIndustrialHomepage from "./profiles/example-industrial-homepage.json"
import ngsProfile from "./profiles/ngs.json"
import ngsHomepage from "./profiles/ngs-homepage.json"

export const generatedProfileBundles = {
  "example-audio": {
    profile: exampleAudioProfile,
    homepage: exampleAudioHomepage,
  },
  "example-industrial": {
    profile: exampleIndustrialProfile,
    homepage: exampleIndustrialHomepage,
  },
  "ngs": {
    profile: ngsProfile,
    homepage: ngsHomepage,
  },
}
