export const DEFAULT_ASSETS = [
  {
    id: "default-home-hero",
    label: "Hero principal NGS",
    url: "/images/ngs/home-hero-ngs-speakers.png",
    alt: "Altavoces profesionales NGS",
    type: "hero",
    client_profile_id: "ngs",
    tags: "home, hero, ngs",
    sort_order: 10,
  },
  {
    id: "default-home-detail",
    label: "Detalle tweeter",
    url: "/images/ngs/home-detail-tweeter.jpg",
    alt: "Detalle de altavoz profesional",
    type: "homepage",
    client_profile_id: "ngs",
    tags: "home, detalle",
    sort_order: 20,
  },
  {
    id: "default-home-range",
    label: "Gama de altavoces",
    url: "/images/ngs/home-range-speakers.jpg",
    alt: "Gama profesional de altavoces",
    type: "homepage",
    client_profile_id: "ngs",
    tags: "home, categoria",
    sort_order: 30,
  },
  {
    id: "default-logo",
    label: "Logo NGS textual",
    url: "/images/ngs/electronics-logo.png",
    alt: "Logo NGS",
    type: "logo",
    client_profile_id: "ngs",
    tags: "logo, brand",
    sort_order: 40,
  },
] as const;
